name: Clone Repository
on:
  push: # On every push on any branch
jobs:
  Build: # Job name
    runs-on: ubuntu-latest # Operating system selection
    steps:
      - uses: actions/setup-java@v5 
        with: 
          java-version: 25
      - name: Build
        run: ./gradlew check